version: '3.3'
services:
  ubuntu:
    build: 
      context: .
      dockerfile: Dockerfile  
    command: 'echo "hola comando desde el docker"'
    container_name: prueba_test
    ports:
      - 9000:8080